version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: my-api-image
    ports:
      - "5000:80"
    secrets:
      - source: mssqldb-connectionstring
        target: connection_string 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    image: my-web-image
    ports:
      - "5001:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  mssqldb-connectionstring:
    external: true
