version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: ghcr.io/mikkelvibeucn/tilbudsavisscraper-api:latest
    ports:
      - "5001:80"  # Host 5001 -> Container 80
    environment:
      - ASPNETCORE_URLS=http://+:80
    secrets:
      - source: mssqldb-connectionstring
        target: connection_string 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    image: ghcr.io/mikkelvibeucn/tilbudsavisscraper-web:latest
    ports:
      - "5000:8080"  # Host 5000 -> Container 8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  mssqldb-connectionstring:
    external: true
