name: Build, Push, and Deploy

on:
  push:
    branches: [ CICD ]
    paths:
      - 'docker/**'
      - 'ScraperLibrary/**'
      - 'APIIntegrationLibrary/**'
      - 'docker-compose.yml'
      - '.github/**'
      - 'AutomaticScraperConsoleApp/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name and Git SHA
        id: vars
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push AutomaticScraperConsoleApp image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.scraper
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-scraper:${{ env.GIT_SHA }}
            ghcr.io/${{ env.IMAGE_NAME }}-scraper:latest


      - name: Deploy to homeserver
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOMESERVER_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOMESERVER_HOST }} >> ~/.ssh/known_hosts

          ssh root@${{ secrets.HOMESERVER_HOST }} << 'EOF'
            set -e
            cd /var/apps/Scraper/TilbudsAvisScraper
            git pull
            docker pull ghcr.io/${{ env.IMAGE_NAME }}-scraper:latest
            docker stop scraper-container || true
            docker rm scraper-container || true
            docker run -d --name scraper-container ghcr.io/${{ env.IMAGE_NAME }}-scraper:latest

          EOF
