name: Scraper API - Build and Deploy

on:
  push:
    branches: [ refactoredscraper ]
    paths:
      - 'Scraper/**'
      - 'APIIntegrationLibrary/**'
      - 'docker-compose.yml'
      - '.github/**'
      - 'Scraper/Dockerfile.api'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name and Git SHA
        id: vars
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Scraper API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Scraper/Dockerfile.api
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-api:${{ env.GIT_SHA }}
            ghcr.io/${{ env.IMAGE_NAME }}-api:latest

      - name: Deploy to Home Server
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOMESERVER_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOMESERVER_HOST }} >> ~/.ssh/known_hosts

          ssh root@${{ secrets.HOMESERVER_HOST }} << 'EOF'
            set -e
            cd /var/apps/NewScraper/TilbudsAvisScraper/Scraper
            git pull

            echo "Redeploying Docker stack..."
            docker pull ghcr.io/${{ github.repository }}-api:latest
            docker stack deploy -c docker-compose.yml scraper
          EOF
