name: Build, Push, and Deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'docker/**'
      - 'TilbudsAvisWeb/**'
      - 'TilbudsAvisScraperAPI/**'
      - 'ScraperLibrary/**'
      - 'DAL/**'
      - 'APIIntegrationLibrary/**'
      - 'docker-compose.yml'
      - '.github/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name and Git SHA
        id: vars
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-api:${{ env.GIT_SHA }}
            ghcr.io/${{ env.IMAGE_NAME }}-api:latest

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.web
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-web:${{ env.GIT_SHA }}
            ghcr.io/${{ env.IMAGE_NAME }}-web:latest

      - name: Deploy to VPS
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

          ssh root@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd /var/apps/TilbudsFinderWeb/TilbudsAvisScraper
            git pull
            docker compose -f docker-compose.yml pull
            docker stack deploy -c docker-compose.yml TilbudsFinder
          EOF
